apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2023-05-29T11:20:29Z'
  generation: 29
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2023-06-02T12:01:33Z'
  name: new-pipeline
  namespace: youssef-project
  resourceVersion: '88058529'
  uid: 66a545f9-d465-4731-a504-69ec5ece5155
spec:
  params:
    - default: sqp_48af2966eef1a74f12aa7cf857d9b574839b8907
      name: sonar.token
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/youssef4898/ez-learning.git'
        - name: revision
          value: master
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:fb10f18e6b984584c114a30a5201a0426820d292e9efc982b2cdfed71a2a6930
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: maven
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - package
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - sonarqube-scanner
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: pipeline-workspace
        - name: maven-settings
          workspace: pipeline-workspace
    - name: buildah
      params:
        - name: IMAGE
          value: 'joseph1998/myinternship:ez-buildah-image2'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:ac0b8714cc260c94435cab46fe41b3de0ccbc3d93e38c395fa9d52ac49e521fe
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: SKIP_PUSH
          value: 'false'
        - name: PUSH_EXTRA_ARGS
          value: '--creds joseph1998:123456789'
      runAfter:
        - maven
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: sonarqube-scanner
      params:
        - name: SONAR_HOST_URL
          value: 'http://sonarqube-route-youssef-project.apps.ocp4.smartek.ae'
        - name: SONAR_PROJECT_KEY
          value: sonarqube-internship
        - name: PROJECT_VERSION
          value: '1.0'
        - name: SOURCE_TO_SCAN
          value: .
        - name: SONAR_ORGANIZATION
          value: default
        - name: SONAR_SCANNER_IMAGE
          value: >-
            docker.io/sonarsource/sonar-scanner-cli:4.6@sha256:7a976330a8bad1beca6584c1c118e946e7a25fdc5b664d5c0a869a6577d81b4f
        - name: SONAR_LOGIN_KEY
          value: login
        - name: SONAR_PASSWORD_KEY
          value: sonar-pwd
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: sonarqube-scanner
      workspaces:
        - name: source
          workspace: pipeline-workspace
        - name: sonar-credentials
          workspace: credentials
  workspaces:
    - name: pipeline-workspace
    - name: credentials
